"use strict";
exports.__esModule = true;
var angular_transistor_module_1 = require("./src/angular-transistor.module");
exports.AngularTransistorModule = angular_transistor_module_1.AngularTransistorModule;
var tabs_component_1 = require("./src/tabs/tabs.component");
exports.TabsComponent = tabs_component_1.TabsComponent;
var tab_component_1 = require("./src/tabs/tab/tab.component");
exports.TabComponent = tab_component_1.TabComponent;
var tabs_service_1 = require("./src/tabs/tabs.service");
exports.TabsService = tabs_service_1.TabsService;
var modal_component_1 = require("./src/modals/modal.component");
exports.ModalComponent = modal_component_1.ModalComponent;
var modals_service_1 = require("./src/modals/modals.service");
exports.ModalsService = modals_service_1.ModalsService;
var angular_transistor_config_1 = require("./src/angular-transistor.config");
exports.angularTransistorConfig = angular_transistor_config_1.angularTransistorConfig;
